################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Adaptable Systems Group By [Julz Insight](https://julzinsight.netlify.app/)"

